
name: craft
#prefix: /your/custom/path/envs/craft
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.6
  - pip=19.3.1
  - pytorch::pytorch>=1.4.0
  - pytorch::torchvision>=0.5.0
  - pip:
    - scikit-image==0.14.2
    - opencv-python==3.4.2.17
    - scipy==1.4.1
    - pytesseract==0.3.3
